### ISSUE TITLE
docker / docker-compose

### ISSUE THREAD

**Issue by ghost** [rikenmehta03/imsearch#2]
Hi,

Hope you are all well !

It would be awesome to create a docker-compose stack to test the project quickly.

Is it on your roadmap ? Do you want me to dockerize it ?

Cheers,
X

**Comment by rikenmehta03** [comment]
Hi X,
I am well. I think it is a good idea. Let's discuss it and for sure you can work on that. It would be great.

**Comment by ghost** [comment]
I was thinking about something like that:

```
|- docker-compose.gpu.yml
|  |- imsearch-gpu:ubuntu
|  |- redis:alpine
|  |- mongodb:alpine 
|
|- docker-compose.yml
|  |- imsearch-cpu:ubuntu 
|  |- redis:alpine
|  |- mongodb:alpine 
```
## about imsearch dockerfiles

### GPU version
- https://github.com/ultralytics/yolov3
- https://github.com/DeNA/PyTorch_YOLOv3
- or one of those images https://github.com/anibali/docker-pytorch

### CPU version 
- https://github.com/ufoym/deepo/blob/master/docker/Dockerfile.pytorch-py36-cpu
- https://github.com/zironycho/pytorch-docker

Hope that clarify my strategy for a pull request.

**Comment by rikenmehta03** [comment]
Looks good to me. You can go ahead and create a pull request. Would you be able to integrate it with GitHub actions? As you might have observed we are using github actions for test.

**Comment by ghost** [comment]
Definitely, I'll try for github actions, first time.
Already started, https://github.com/x0rzkov/imsearch

**Comment by ghost** [comment]
I have an error while testing imsearch inside a docker container:

```bash
root@9ee0e1e73a15:/imsearch/examples# python3 index.py
Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /root/.cache/torch/checkpoints/resnet50-19c8e357.pth
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 97.8M/97.8M [00:04<00:00, 23.5MB/s]
Running extractor
 90% [...............................................................       ] 223600640 / 248007048Traceback (most recent call last):
  File "index.py", line 64, in <module>
    index = create_index('test', all_images[:25])
  File "index.py", line 14, in create_index
    index.cleanIndex()
  File "/usr/local/lib/python3.6/dist-packages/imsearch/index.py", line 110, in cleanIndex
    self._repository_db.clean()
  File "/usr/local/lib/python3.6/dist-packages/imsearch/repository/__init__.py", line 16, in clean
    self.db.clean()
  File "/usr/local/lib/python3.6/dist-packages/imsearch/repository/mongo.py", line 11, in clean
    self.db.drop()
  File "/usr/local/lib/python3.6/dist-packages/pymongo/collection.py", line 1103, in drop
    dbo.drop_collection(self.__name, session=session)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/database.py", line 914, in drop_collection
    with self.__client._socket_for_writes(session) as sock_info:
  File "/usr/local/lib/python3.6/dist-packages/pymongo/mongo_client.py", line 1266, in _socket_for_writes
    server = self._select_server(writable_server_selector, session)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/mongo_client.py", line 1253, in _select_server
    server = topology.select_server(server_selector)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/topology.py", line 235, in select_server
    address))
  File "/usr/local/lib/python3.6/dist-packages/pymongo/topology.py", line 193, in select_servers
    selector, server_timeout, address)
  File "/usr/local/lib/python3.6/dist-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
```

despite I have setup the env vars for mongodb an redis in the docker-compose:
```yaml
---
version: '3.7'
services:

  imsearch:
    image: imsearch-cpu:latest
    container_name: ${NAMESPACE}-cpu
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 5000:5000
    environment:
    - MONGO_URI='mongodb://mongodb:27017/',
    - REDIS_URI='redis://redis:6379/0',
    depends_on:
    - redis
    - mongodb
    links:
    - mongodb:mongodb
    - redis:redis
    networks:
    - internal
    - web
```

Any idea how to solve it ?
Shall I do a pull request and we discuss about it here ?

Cheers,
X

**Comment by rikenmehta03** [comment]
Can you check if the mongodb container is running? 
`docker container ls`

**Comment by ghost** [comment]
Yes, everything is running. I had to change imsearch/config.py and examples/index.py to docker-compose hosts and it worked. So I guess there is a mix up with the env variables and some hard coded things.

Also, can you provide some image examples by default in the repo ?

**Comment by rikenmehta03** [comment]
Okay. I think I understand what is happening. Intention is to pass the environment variables with index initialization. Currently system does not support getting the variables exposed in env. Do you want me to fix that in `master`. You can pull it then and it should work without any changes in `config.py`. Although I am gonna make changes in that file only.  

Yes. I can provide image in the same fix.

**Comment by ghost** [comment]
Yes, fix the master. I ll test on my side as I have not finished github actions.

**Comment by rikenmehta03** [comment]
Fixed the master. Also added example images to work with.

**Comment by ghost** [comment]
I am working on the github actions.

- Do you wanna build and push the images ? 
  - if yes, do you have a docker hub account ?
- Do you wanna test imsearch builds inside docker containers ?

**Comment by rikenmehta03** [comment]
Yes. Building and pushing images would be a good idea. I do have docker hub account. 
Yes. Let's test the builds inside container as well.

**Comment by ghost** [comment]
Sorry for the delay, had lot of tasks to finish first...
I'll do it tomorrow.

**Comment by rikenmehta03** [comment]
Closing this issue with PR #7
