### ISSUE TITLE
multi image detection / multiple occurences / rest api

### ISSUE THREAD

**Issue by ghost** [rikenmehta03/imsearch#3]
Hi,

Hope you are all well !

I was wondering if imsearch is able to make these 3 points:

# Detection of multiple occurrences of the same picture
For example, based on [find-object](https://github.com/introlab/find-object), being able to detect multiple occurences of the same object.
![alt text](https://raw.githubusercontent.com/wiki/introlab/find-object/doc/tutorial4/1.png "Detection of multiple occurrences of the same object")

# Many objects detection
Another example, still based on find-object](https://github.com/introlab/find-object), to detect many objects in a scene.
![alt text](https://raw.githubusercontent.com/wiki/introlab/find-object/doc/tutorial5/results1000.jpg "Detection of multiple occurrences of the same object")

# Rest API
Is there a rest api where you can add meta data for each signatures ?

Thanks in advance for your insights and inputs on these topics.

Cheers,
X

**Comment by rikenmehta03** [comment]
Let me give you answers in points that you asked. 
1. The system does not currently check if the exactly same image exists in the index or not, but the functionality can easily be added. We can discuss the use cases and ways to add to the system if you are interested. 
2. Yes. the back-end system consists of YOLOv3, which is fast and state-of-the art object detection system based on CNN. It can detect multiple object(same or different) in an image. You can checkout more details [here](https://pjreddie.com/darknet/yolo/)
3. No. The framework is python package which do not have any REST apis. It is supposed to be incorporated in the server side code. Also, there is no such feature as of now to add meta-data for images, but I am open to discussion. 

I hope I answered all your queries and it helps you.

**Comment by ghost** [comment]
Hi,

Thanks for the reply.

1. Would be interesting to match image for some specific patterns. Use case, for eg augmented reality. You send a picture from a mobile device to the 'imsearch' rest api, then you send a response with an image Id in order to trigger an interaction based on the matching result. Of course, depending on the score confidence to avoid false/positive.

2. If yes, it can combine matching results for an extended interaction set by multiple image IDs. What could be an interaction ? Display some wikipedia results, and I can do it. I can either provide a mobile client for that.

3. I can do the rest api as I already made one for another project. https://gist.github.com/x0rzkov/111f8081c30c5ed82268bbca30729072. For the meta data, adding those can help out to filter false/positive.

Hopefully, you understood my features request and can sketch some of them partially. As I said, I am ready to contribute fully to make it awesome.

Cheers,
X

**Comment by rikenmehta03** [comment]
My comments on above points. 
1. I think I understood it incorrectly before. Now I see that you want to detect exactly same objects from a single picture. I think what the engine is able to do is correctly detect all the objects in an image. And as of now the scope of the framework is to support the building of image search engine. Let's keep this out of scope for now. 
2. I have this thing in mind like this: Look for the web results/articles/wikis for every image and object in the search result. We can add this in the response object of the search. Creating the separate thread for this. Let's discuss it [here](https://github.com/rikenmehta03/imsearch/issues/4).
3. REST api is not something this framework is going to support. We are only building the back-end framework over which anyone can build the api server. I am currently working on building the search-engine platform using this framework. Although I liked the idea of supporting meta-data along with the images. Creating the issue for this feature. [here](https://github.com/rikenmehta03/imsearch/issues/5)
