### ISSUE TITLE
image recognition / logo-2k

### ISSUE THREAD

**Issue by ghost** [rikenmehta03/imsearch#8]
Hi,

Hope you are all well !

I was wondering if **imsearch** is able to load this dataset of logos and match them in random pictures ?

https://github.com/msn199959/Logo-2k-plus-Dataset

Thanks in advance for your inputs and insights.

Cheers,
X

**Comment by rikenmehta03** [comment]
Hi,
No. It is not customized for this task. Although, you can try building your search index and try querying the index using these logo images. Let me know if that returns images with logos in it.
