### ISSUE TITLE
Custom Feature Extractor

### ISSUE THREAD

**Issue by ohjho** [rikenmehta03/imsearch#9]
i guess this is more of a question than issue

let's say i want to use my own feature extractor (instead of YOLOv3) is there an easy way to accomplish that?

**Comment by rikenmehta03** [comment]
I am assuming you want to change the Object detector. Current implementation use YOLOv3: https://github.com/rikenmehta03/imsearch/tree/master/imsearch/backend/object_detector/yolo
If you want to change that, you can implement the similar `Detector` class for the method you want to use for Object detector. Make sure to return the similar response object that is returned by Detector class here: https://github.com/rikenmehta03/imsearch/blob/master/imsearch/backend/object_detector/yolo/detector.py#L67
Also you should change this method here to return correct Detector: https://github.com/rikenmehta03/imsearch/blob/master/imsearch/backend/object_detector/__init__.py#L4

**Comment by ohjho** [comment]
thanks @rikenmehta03
